module LoremIpsum
	def self.small
		"Nunc vel sollicitudin libero. Nullam at fringilla turpis. Nunc nec varius mi, sed ultrices ante. Nullam vel felis augue. Nulla sapien orci, viverra ut orci eget, iaculis feugiat lacus. Phasellus accumsan mattis nisi id venenatis. Etiam facilisis ligula ac volutpat placerat."
	end

	def self.large
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean laoreet neque vel tempor molestie. Nunc vestibulum augue quis dui ultricies aliquet. Integer eu egestas enim. Ut quis bibendum risus, vitae pulvinar velit. Ut vitae felis dignissim, auctor mauris lobortis, ornare augue. Proin lacus lorem, feugiat sit amet feugiat eget, suscipit a elit. Ut ante nisl, lobortis at varius ut, dictum eu augue. Donec sapien eros, posuere in consectetur at, pretium eu tortor. Nulla facilisi. Donec in nibh rutrum, iaculis odio et, faucibus est. Nunc fermentum libero mi, vel blandit velit auctor non. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eu pharetra erat. Proin dictum non dui id pharetra. Aenean pharetra venenatis fermentum. Curabitur vulputate convallis felis, et suscipit eros molestie sed."
	end

	def self.multiple
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean laoreet neque vel tempor molestie. Nunc vestibulum augue quis dui ultricies aliquet. Integer eu egestas enim. Ut quis bibendum risus, vitae pulvinar velit. Ut vitae felis dignissim, auctor mauris lobortis, ornare augue. Proin lacus lorem, feugiat sit amet feugiat eget, suscipit a elit. Ut ante nisl, lobortis at varius ut, dictum eu augue. Donec sapien eros, posuere in consectetur at, pretium eu tortor. Nulla facilisi. Donec in nibh rutrum, iaculis odio et, faucibus est. Nunc fermentum libero mi, vel blandit velit auctor non. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eu pharetra erat. Proin dictum non dui id pharetra. Aenean pharetra venenatis fermentum. Curabitur vulputate convallis felis, et suscipit eros molestie sed.\r\nNunc vel sollicitudin libero. Nullam at fringilla turpis. Nunc nec varius mi, sed ultrices ante. Nullam vel felis augue. Nulla sapien orci, viverra ut orci eget, iaculis feugiat lacus. Phasellus accumsan mattis nisi id venenatis. Etiam facilisis ligula ac volutpat placerat. \r\n Etiam nec mattis ante, quis ornare diam. Quisque erat urna, sodales ut porttitor et, dictum nec urna. Praesent posuere tortor lectus, nec varius elit fermentum aliquam. In non elit ligula. Pellentesque quis molestie eros. In sodales pretium luctus. Nam congue arcu mauris. Maecenas accumsan nisi viverra iaculis congue. Ut mauris neque, mattis quis est non, interdum venenatis libero. Integer sed dictum ante."
	end
end